version: '3.4'

services:
  rabbitmq:
    container_name: rabbitMq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "5671:5671"
    environment: 
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
  rabbitmq-client:
      build: .
      ports:
        - "8081:8081"
      depends_on:
        - rabbitmq
      links:
        - rabbitmq
  