[general]
active = 1
#   0: development
#   1: docker
#   2: production
#   3: qa
port = 8081

    [general.rabbitmq]
    port = 5672
    connection_type = "amqp"

        [general.rabbitmq.queue]
        name = "scaloutions"
        durable = false
        auto_delete = false
        exclusive = false
        no_wait = false


