[general]
active = 1
#   0: development
#   1: docker
#   2: production
#   3: qa
port = 8081

    [general.rabbitmq]
    port = 5672
    connection_type = "amqp"

        [general.rabbitmq.queue]
        name = "scaloutions"
        durable = true # durable
        auto_delete = false # delete when unused
        exclusive = false # exclusive
        no_wait = false # no-wait (wait time for processing)
    
    [general.cache-server]
    port = 8080
    host = "localhost"


[queue]
durable = true
auto_delete = false
exclusive = false
no_wait = false

    [queue.save]
    name = "save"

    [queue.get-by-key]
    name = "get-by-key"

    [queue.get]
    name = "get"


[api]
api = "/api"
publish = "/publish"

    [api.cache-server]
    api = "/api"
    save = "/save"
    get_by_key = "/get/:stock/:userid"
    get = "/get"
