[general]
active = 1
#   0: development
#   1: docker
#   2: production
#   3: qa
port = 8081

    [general.cache-server]
    port = 8080
    host = "localhost"

    [general.rabbitmq]
    port = 5672
    connection_type = "amqp"

        [general.rabbitmq.queue]
        name = "scaloutions"
        durable = true # durable
        auto_delete = false # delete when unused
        exclusive = false # exclusive
        no_wait = false # no-wait (wait time for processing)


[api]
api = "/api"
publish = "/publish"

    [api.cache-server]
    api = "/api"